language: Java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
deploy:
  provider: heroku
  api_key:
    secure: aGcVcQRh+N+MML47g9E380YOPQ7N8F1k+wcYKDbBnnYXQDZtKpNp9JhUfm+WsrVdwC+B8mJYmYepDVAh1UWTUB0I0drZhzYYZfrcgAIExqNYFDyyPIuaFXwHYa27uFTgDG3W70E/OESzaQip4Yh/X0qbsTLJMICqOujjIhwAxPg0bJhwreEmWnGDmjeeXuHgUjFn4/1E9o5MLg3g7XkaJWOi+ljt/XOjbGWoKSQBJvrBHMiIxdHqR4nE09waoxWPK3V6RqD5BKACT0XkyF9kfpAhNxqa2eXm69xh+BriIVrT1LeAj/jAH6vJcOdsnDPGMxMsaXSovVvjsL/8AkL9ck45QlnylyFSyDgrz0/Mb3VlkaGqJMfqIuqxvjwEg/apOucgqntBfJ+oWzQnWjgxH3O84GKw+6VuLOu5dlr745OGBLBO05dimWPcyOQ8pbxyAPu9COXx56VgbTOgiuBozVk4CUHmM+XgRuc91exourOmezCppiYQZXHs8PP6V6H2Weo4ZraePJ/4YE5SPiH/bmzltv5eWoiStJzdS/jzgGQKOhKvrEMVEq2SnxKbmXSAGTDPTtoTIOXtMh5+dm8O+atMAaWcqi5rRjdGHCJP9piDI6MiDt3t9NndpFczrpvbRTHf7XavUfl5Tulhn1j5UfF1tN8wLHFdk7i3vgCUpeI=
  app: jalgoarena-api
  on:
    repo: spolnik/JAlgoArena-API
