server:
  port: 5001

zuul:
  ignoredServices: '*'
  routes:
    jalgoarena-judge: /judge/**
    jalgoarena-problems: /problems/**
    jalgoarena-auth: /auth/**
    jalgoarena-submissions: /submissions/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000/eureka/}

hystrix:
  command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${APP_NAME}.herokuapp.com
    nonSecurePort: 80

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
