server:
  port: 5001

zuul:
  ignoredServices: '*'
  routes:
    judge-agent: /judge-agent/**
    problems-service: /problems-service/**
    auth-service: /auth-service/**
    submissions-service: /submissions-service/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000/eureka/}
---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO