server:
  port: 5001

zuul:
  ignoredServices: '*'
  routes:
    jalgoarena-judge: /judge/**
    jalgoarena-problems: /problems/**
    jalgoarena-auth: /auth/**
    jalgoarena-submissions: /submissions/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000/eureka/}
---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
